"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
from decouple import config
from django.core.exceptions import ImproperlyConfigured

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


def csv_config(name, default=""):
    return config(
        name,
        default=default,
        cast=lambda value: [
            item.strip() for item in value.split(",") if item.strip()
        ],
    )


# Production must provide its own secret through the environment.
DEBUG = config("DEBUG", default="development").strip().lower() in (
    "1",
    "true",
    "yes",
    "on",
    "development",
    "debug",
)
SECRET_KEY = config("SECRET_KEY", default=None)
if not SECRET_KEY:
    if not DEBUG:
        raise ImproperlyConfigured(
            "La variable de entorno SECRET_KEY es obligatoria en producción."
        )
    SECRET_KEY = "unsafe-local-development-key"

ALLOWED_HOSTS = csv_config("ALLOWED_HOSTS", "localhost,127.0.0.1")


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'rest_framework',
    'drf_spectacular',
    'django_filters',
    'core',
    'usuarios',
    'organizacion',
    'inventario',
    'operacion',
    'conocimiento',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    "corsheaders.middleware.CorsMiddleware",
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
     "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": config("DB_NAME"),
        "USER": config("DB_USER"),
        "PASSWORD": config("DB_PASSWORD"),
        "HOST": config("DB_HOST"),
        "PORT": config("DB_PORT", cast=int),
    }
}

# Allow using SQLite in CI or local dev by setting USE_SQLITE=True
if config("USE_SQLITE", default=False, cast=bool):
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]



LANGUAGE_CODE = "es"

TIME_ZONE = "America/Asuncion"

USE_I18N = True

USE_TZ = True

STATIC_URL = "/static/"
STATIC_ROOT = BASE_DIR / "staticfiles"
MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"
AUTH_USER_MODEL = "usuarios.Usuario"

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ),

    "DEFAULT_PERMISSION_CLASSES": (
        "rest_framework.permissions.IsAuthenticated",
    ),

    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",

    "DEFAULT_FILTER_BACKENDS": (
        "django_filters.rest_framework.DjangoFilterBackend",
        "rest_framework.filters.SearchFilter",
        "rest_framework.filters.OrderingFilter",
    ),

    "DEFAULT_PAGINATION_CLASS": (
        "core.api.pagination.PaginacionEstandar"
    ),
}

SPECTACULAR_SETTINGS = {
    "TITLE": "ITDATA API",
    "DESCRIPTION": "API REST para la gestión operativa del área de TI.",
    "VERSION": "1.0.0",
    "SERVE_INCLUDE_SCHEMA": False,
    "ENUM_NAME_OVERRIDES": {
        "TicketEstadoEnum": [
            ("NUEVO", "Nuevo"),
            ("ASIGNADO", "Asignado"),
            ("EN_PROCESO", "En proceso"),
            ("ESPERANDO_USUARIO", "Esperando usuario"),
            ("ESPERANDO_PROVEEDOR", "Esperando proveedor"),
            ("ESPERANDO_OTRA_AREA", "Esperando otra área"),
            ("EN_PRUEBAS", "En pruebas"),
            ("RESUELTO", "Resuelto"),
            ("CANCELADO", "Cancelado"),
        ],
        "ActivoEstadoEnum": [
            ("OPERATIVO", "Operativo"),
            ("EN_REPARACION", "En reparación"),
            ("FUERA_SERVICIO", "Fuera de servicio"),
            ("BAJA", "Baja"),
        ],
        "ArticuloConocimientoEstadoEnum": [
            ("BORRADOR", "Borrador"),
            ("EN_REVISION", "En revisión"),
            ("PUBLICADO", "Publicado"),
            ("ARCHIVADO", "Archivado"),
        ],
    },
}

CORS_ALLOWED_ORIGINS = csv_config(
    "CORS_ALLOWED_ORIGINS", "http://localhost:4200"
)
CSRF_TRUSTED_ORIGINS = csv_config("CSRF_TRUSTED_ORIGINS")

SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
USE_X_FORWARDED_HOST = True
SECURE_SSL_REDIRECT = config("SECURE_SSL_REDIRECT", default=False, cast=bool)
SESSION_COOKIE_SECURE = SECURE_SSL_REDIRECT
CSRF_COOKIE_SECURE = SECURE_SSL_REDIRECT
SECURE_HSTS_SECONDS = config("SECURE_HSTS_SECONDS", default=0, cast=int)
SECURE_HSTS_INCLUDE_SUBDOMAINS = SECURE_HSTS_SECONDS > 0
SECURE_HSTS_PRELOAD = SECURE_HSTS_SECONDS > 0

# Microsoft Graph. Son opcionales hasta que una integración solicite un cliente.
MS_GRAPH_TENANT_ID = config("MS_GRAPH_TENANT_ID", default="")
MS_GRAPH_CLIENT_ID = config("MS_GRAPH_CLIENT_ID", default="")
MS_GRAPH_CLIENT_SECRET = config("MS_GRAPH_CLIENT_SECRET", default="")
MS_GRAPH_MAILBOX = config("MS_GRAPH_MAILBOX", default="")
