# Generated by Django 6.0.7 on 2026-07-20 15:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventario', '0001_initial'),
        ('operacion', '0002_alter_historialticket_tipo_movimiento_adjuntoticket_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticuloConocimiento',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('codigo', models.CharField(editable=False, max_length=20, unique=True)),
                ('titulo', models.CharField(max_length=180)),
                ('resumen', models.TextField()),
                ('sintomas', models.TextField(blank=True)),
                ('diagnostico', models.TextField(blank=True)),
                ('causa', models.TextField(blank=True)),
                ('procedimiento_solucion', models.TextField(blank=True)),
                ('palabras_clave', models.CharField(blank=True, help_text='Palabras separadas por coma para facilitar la búsqueda.', max_length=250)),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('EN_REVISION', 'En revisión'), ('PUBLICADO', 'Publicado'), ('ARCHIVADO', 'Archivado')], default='BORRADOR', max_length=20)),
                ('fecha_publicacion', models.DateTimeField(blank=True, null=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='articulos_conocimiento_creados', to=settings.AUTH_USER_MODEL)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='articulos_conocimiento', to='operacion.categoria')),
                ('revisado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='articulos_conocimiento_revisados', to=settings.AUTH_USER_MODEL)),
                ('subcategoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='articulos_conocimiento', to='operacion.subcategoria')),
                ('tickets_relacionados', models.ManyToManyField(blank=True, related_name='articulos_conocimiento', to='operacion.ticket')),
                ('tipo_activo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articulos_conocimiento', to='inventario.tipoactivo')),
            ],
            options={
                'verbose_name': 'Artículo de conocimiento',
                'verbose_name_plural': 'Artículos de conocimiento',
                'ordering': ('-fecha_modificacion',),
            },
        ),
    ]
