# Generated by Django 6.0.7 on 2026-07-16 17:20

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventario', '0001_initial'),
        ('organizacion', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.CharField(blank=True, max_length=250)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Subcategoria',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(blank=True, max_length=250)),
                ('activo', models.BooleanField(default=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subcategorias', to='operacion.categoria')),
            ],
            options={
                'verbose_name': 'Subcategoría',
                'verbose_name_plural': 'Subcategorías',
                'ordering': ['categoria__nombre', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('numero', models.PositiveBigIntegerField(editable=False, unique=True)),
                ('codigo', models.CharField(editable=False, max_length=30, unique=True)),
                ('titulo', models.CharField(max_length=150)),
                ('descripcion', models.TextField()),
                ('origen', models.CharField(choices=[('PORTAL_SUCURSAL', 'Portal de sucursal'), ('WHATSAPP', 'WhatsApp'), ('LLAMADA', 'Llamada'), ('CORREO', 'Correo'), ('PRESENCIAL', 'Presencial'), ('TECNICO', 'Creado por técnico'), ('MONITOREO', 'Sistema de monitoreo')], default='PORTAL_SUCURSAL', max_length=30)),
                ('estado', models.CharField(choices=[('NUEVO', 'Nuevo'), ('ASIGNADO', 'Asignado'), ('EN_PROCESO', 'En proceso'), ('ESPERANDO_USUARIO', 'Esperando usuario'), ('ESPERANDO_PROVEEDOR', 'Esperando proveedor'), ('ESPERANDO_OTRA_AREA', 'Esperando otra área'), ('EN_PRUEBAS', 'En pruebas'), ('RESUELTO', 'Resuelto'), ('CERRADO', 'Cerrado'), ('CANCELADO', 'Cancelado')], default='NUEVO', max_length=30)),
                ('prioridad_sugerida', models.CharField(blank=True, choices=[('BAJA', 'Baja'), ('MEDIA', 'Media'), ('ALTA', 'Alta'), ('CRITICA', 'Crítica')], editable=False, max_length=10)),
                ('prioridad_final', models.CharField(blank=True, choices=[('BAJA', 'Baja'), ('MEDIA', 'Media'), ('ALTA', 'Alta'), ('CRITICA', 'Crítica')], max_length=10)),
                ('motivo_cambio_prioridad', models.TextField(blank=True)),
                ('responsable_actual', models.CharField(choices=[('TI', 'Tecnología'), ('SUCURSAL', 'Sucursal'), ('USUARIO', 'Usuario'), ('PROVEEDOR', 'Proveedor'), ('COMPRAS', 'Compras'), ('FINANZAS', 'Finanzas'), ('OTRA_AREA', 'Otra área')], default='TI', max_length=20)),
                ('fecha_reporte', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_toma', models.DateTimeField(blank=True, null=True)),
                ('fecha_resolucion', models.DateTimeField(blank=True, null=True)),
                ('fecha_cierre', models.DateTimeField(blank=True, null=True)),
                ('solucion', models.TextField(blank=True)),
                ('activo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='inventario.activo')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='operacion.categoria')),
                ('cerrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets_cerrados', to=settings.AUTH_USER_MODEL)),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets_creados', to=settings.AUTH_USER_MODEL)),
                ('resuelto_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets_resueltos', to=settings.AUTH_USER_MODEL)),
                ('subcategoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='operacion.subcategoria')),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='organizacion.sucursal')),
                ('tecnico_asignado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets_asignados', to=settings.AUTH_USER_MODEL)),
                ('tomado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets_tomados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ticket',
                'verbose_name_plural': 'Tickets',
                'ordering': ['-numero'],
            },
        ),
        migrations.CreateModel(
            name='HistorialTicket',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('tipo_movimiento', models.CharField(choices=[('CREACION', 'Creación'), ('ASIGNACION', 'Asignación'), ('CAMBIO_ESTADO', 'Cambio de estado'), ('CAMBIO_PRIORIDAD', 'Cambio de prioridad'), ('CAMBIO_RESPONSABLE', 'Cambio de responsable'), ('COMENTARIO', 'Comentario'), ('RESOLUCION', 'Resolución'), ('CIERRE', 'Cierre')], max_length=30)),
                ('comentario', models.TextField()),
                ('estado_anterior', models.CharField(blank=True, max_length=30)),
                ('estado_nuevo', models.CharField(blank=True, max_length=30)),
                ('prioridad_anterior', models.CharField(blank=True, max_length=10)),
                ('prioridad_nueva', models.CharField(blank=True, max_length=10)),
                ('responsable_anterior', models.CharField(blank=True, max_length=20)),
                ('responsable_nuevo', models.CharField(blank=True, max_length=20)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_tickets', to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='operacion.ticket')),
            ],
            options={
                'verbose_name': 'Historial de ticket',
                'verbose_name_plural': 'Historial de tickets',
                'ordering': ['fecha_creacion'],
            },
        ),
        migrations.AddConstraint(
            model_name='subcategoria',
            constraint=models.UniqueConstraint(fields=('categoria', 'nombre'), name='operacion_subcategoria_unica_por_categoria'),
        ),
    ]
