# Generated by Django 6.0.7 on 2026-07-20 11:47

import django.core.validators
import django.db.models.deletion
import operacion.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operacion', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='historialticket',
            name='tipo_movimiento',
            field=models.CharField(choices=[('CREACION', 'Creación'), ('ASIGNACION', 'Asignación'), ('CAMBIO_ESTADO', 'Cambio de estado'), ('CAMBIO_PRIORIDAD', 'Cambio de prioridad'), ('CAMBIO_RESPONSABLE', 'Cambio de responsable'), ('COMENTARIO', 'Comentario'), ('ADJUNTO', 'Archivo adjunto'), ('RESOLUCION', 'Resolución'), ('CIERRE', 'Cierre')], max_length=30),
        ),
        migrations.CreateModel(
            name='AdjuntoTicket',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('archivo', models.FileField(upload_to=operacion.models.ruta_adjunto_ticket, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('pdf', 'png', 'jpg', 'jpeg', 'txt', 'log', 'csv', 'docx', 'xlsx')), operacion.models.validar_tamano_adjunto])),
                ('nombre_original', models.CharField(max_length=255)),
                ('descripcion', models.CharField(blank=True, max_length=250)),
                ('subido_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='adjuntos_tickets', to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjuntos', to='operacion.ticket')),
            ],
            options={
                'verbose_name': 'Adjunto de ticket',
                'verbose_name_plural': 'Adjuntos de tickets',
                'ordering': ('fecha_creacion',),
            },
        ),
        migrations.CreateModel(
            name='ComentarioTicket',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('tipo', models.CharField(choices=[('NOTA', 'Nota'), ('DIAGNOSTICO', 'Diagnóstico'), ('ACCION_REALIZADA', 'Acción realizada'), ('RESPUESTA_USUARIO', 'Respuesta del usuario')], default='NOTA', max_length=30)),
                ('texto', models.TextField()),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comentarios_tickets', to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='operacion.ticket')),
            ],
            options={
                'verbose_name': 'Comentario de ticket',
                'verbose_name_plural': 'Comentarios de tickets',
                'ordering': ('fecha_creacion',),
            },
        ),
    ]
