# Generated by Django 6.0.7 on 2026-07-17 15:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizacion', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='sucursal',
            field=models.ForeignKey(blank=True, help_text='Sucursal propia del usuario con rol Sucursal.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios', to='organizacion.sucursal'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='sucursales_asignadas',
            field=models.ManyToManyField(blank=True, help_text='Sucursales que puede gestionar un usuario con rol Jefe de Distrito.', related_name='jefes_distrito', to='organizacion.sucursal'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('ADMINISTRADOR', 'Administrador'), ('SUPERVISOR', 'Supervisor'), ('TECNICO', 'Técnico'), ('JDISTRITO', 'Jefe de Distrito'), ('SUCURSAL', 'Sucursal'), ('CONSULTOR', 'Consultor')], default='SUCURSAL', max_length=20),
        ),
    ]
