# Generated by Django 6.0.7 on 2026-07-16 16:52

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NumeradorDocumento',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('clave', models.CharField(help_text='Identificador interno. Ejemplo: TICKET', max_length=30, unique=True)),
                ('nombre', models.CharField(help_text='Nombre descriptivo. Ejemplo: Tickets', max_length=100)),
                ('prefijo', models.CharField(default='ITD', help_text='Texto que aparecerá antes del número.', max_length=20)),
                ('ultimo_numero', models.PositiveBigIntegerField(default=0)),
                ('longitud', models.PositiveSmallIntegerField(default=6, help_text='Cantidad de dígitos. Ejemplo: 6 genera 000001.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Numerador de documento',
                'verbose_name_plural': 'Numeradores de documentos',
                'ordering': ['nombre'],
            },
        ),
    ]
